## DB Settings
spring:
  datasource:
    url: jdbc:mysql://localhost/facediary_db
    username: root
    password: root1219
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: facediary1234@gmail.com
    password: eqhmwcvyqcateben
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# S3
cloud:
  aws:
    credentials:
      accessKey: AKIAT7N5KMTBG5HVTOEK
      secretKey: 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
    s3:
      bucket: facediary-app
    region:
      static: ap-northeast-1
    stack:
      auto: false